### ISSUE TITLE
Time is wrong

### ISSUE THREAD

**Issue by johnwyz88** [Trinovantes/Quest-Schedule-Exporter#1]
For some reason, the time range is completely off. See exported data:

BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//Stephen Li//Quest Schedule Exporter//EN
BEGIN:VEVENT
DTSTART;TZID=America/Toronto:19030406T143000
DTEND;TZID=America/Toronto:19030406T172000
RRULE:FREQ=WEEKLY;UNTIL=20931207T235900;WKST=SU;BYDAY=MO
SUMMARY:EARTH 121 LEC in AL 116
LOCATION:AL 116
DESCRIPTION:EARTH 121-001: Introductory (LEC) in AL 116 with John Johnston 20
END:VEVENT
BEGIN:VEVENT
DTSTART;TZID=America/Toronto:19060405T173000
DTEND;TZID=America/Toronto:19060405T182000
RRULE:FREQ=WEEKLY;UNTIL=20931207T235900;WKST=SU;BYDAY=TH
SUMMARY:ECE 400A SEM in RCH 101
LOCATION:RCH 101
DESCRIPTION:ECE 400A-001: ECE (SEM) in RCH 101 with Hiren Patel 20
END:VEVENT
BEGIN:VEVENT
DTSTART;TZID=America/Toronto:19040405T093000
DTEND;TZID=America/Toronto:19040405T102000
RRULE:FREQ=WEEKLY;UNTIL=20931207T235900;WKST=SU;BYDAY=TU,WE,TH
SUMMARY:ECE 454 LEC in MC 1085
LOCATION:MC 1085
DESCRIPTION:ECE 454-001: Distributed (LEC) in MC 1085 with Wojciech Golab 20
END:VEVENT
BEGIN:VEVENT
DTSTART;TZID=America/Toronto:19030406T100000
DTEND;TZID=America/Toronto:19030406T112000
RRULE:FREQ=WEEKLY;UNTIL=20931207T235900;WKST=SU;BYDAY=MO,FR
SUMMARY:ECE 457A LEC in RCH 101
LOCATION:RCH 101
DESCRIPTION:ECE 457A-001: Coop (LEC) in RCH 101 with Otman Basir 20
END:VEVENT
BEGIN:VEVENT
DTSTART;TZID=America/Toronto:19040405T083000
DTEND;TZID=America/Toronto:19040405T092000
RRULE:FREQ=WEEKLY;UNTIL=20931207T235900;WKST=SU;BYDAY=TU,WE,TH
SUMMARY:ECE 458 LEC in RCH 101
LOCATION:RCH 101
DESCRIPTION:ECE 458-001: Computer (LEC) in RCH 101 with Mahesh Tripunitara 20
END:VEVENT
BEGIN:VEVENT
DTSTART;TZID=America/Toronto:19040405T163000
DTEND;TZID=America/Toronto:19040405T172000
RRULE:FREQ=WEEKLY;UNTIL=20701205T235900;WKST=SU;BYDAY=TU
SUMMARY:ECE 458 TUT in RCH 302
LOCATION:RCH 302
DESCRIPTION:ECE 458-101: Computer (TUT) in RCH 302 with Staff 20
END:VEVENT
BEGIN:VEVENT
DTSTART;TZID=America/Toronto:19030407T173000
DTEND;TZID=America/Toronto:19030407T182000
RRULE:FREQ=WEEKLY;UNTIL=20931207T235900;WKST=SU;BYDAY=TU
SUMMARY:ECE 498A PRJ in RCH 101
LOCATION:RCH 101
DESCRIPTION:ECE 498A-001: Engineering (PRJ) in RCH 101 with Dana Kulic\, Daniel Davison 20
END:VEVENT
END:VCALENDAR

**Comment by Trinovantes** [comment]
Can you post your raw input from quest, minus any private info?

**Comment by johnwyz88** [comment]
GO!

<Name>

My Academics

Course Selection (Undergrad only)

Enroll

GO Pass

my class schedule

add

drop

swap

component swap

appointments

search for classes

My Class Schedule (Download Schedule)
List View
Weekly Calendar View
Select Display Option
change term
Spring 2016 | Undergraduate | University of Waterloo
BET 410A - Cap Entre Planning Exec Pt 1
Status  Units   Grading Grade
Enrolled
0.25
Numeric Grading Basis

Class Nbr   Section Component   Days & Times    Room    Instructor  Start/End Date
3330
001
LEC

TBA
Douglas Sparkes
2016/05/02 - 2016/07/26
Exam Information

EARTH 121 - Introductory Earth Sciences
Status  Units   Grading Grade
Enrolled
0.50
Numeric Grading Basis

Class Nbr   Section Component   Days & Times    Room    Instructor  Start/End Date
4229
001
LEC
M 2:30PM - 5:20PM
AL    116
John Johnston
2016/05/02 - 2016/07/26
Exam Information

ECE 400A - ECE Practice
Status  Units   Grading Grade   Requirement Designation
Enrolled
0.10
Credit/No Credit, No Fail Grd Category

Degree Requirement, Not in Avg, Not in Fail Count (Taken)
Class Nbr   Section Component   Days & Times    Room    Instructor  Start/End Date
3228
001
SEM
Th 5:30PM - 6:20PM
RCH   101
Hiren Patel
2016/05/05 - 2016/07/26
Exam Information

ECE 454 - Distributed Computing
Status  Units   Grading Grade
Enrolled
0.50
Numeric Grading Basis

Class Nbr   Section Component   Days & Times    Room    Instructor  Start/End Date
2749
001
LEC
TWTh 9:30AM - 10:20AM
MC   1085
Wojciech Golab
2016/05/03 - 2016/07/26
2750
101
TUT
TBA
TBA
Staff
2016/05/02 - 2016/07/26
3071
201
LAB
TBA
TBA
Staff
2016/05/02 - 2016/07/26
Exam Information

ECE 457A - Coop & Adaptive Algorithms
Status  Units   Grading Grade
Enrolled
0.50
Numeric Grading Basis

Class Nbr   Section Component   Days & Times    Room    Instructor  Start/End Date
3058
001
LEC
MF 10:00AM - 11:20AM
RCH   101
Otman Basir
2016/05/02 - 2016/07/26
3059
101
TUT
TBA
TBA
Staff
2016/05/02 - 2016/07/26
Exam Information

ECE 458 - Computer Security
Status  Units   Grading Grade
Enrolled
0.50
Numeric Grading Basis

Class Nbr   Section Component   Days & Times    Room    Instructor  Start/End Date
3231
001
LEC
TWTh 8:30AM - 9:20AM
RCH   101
Mahesh Tripunitara
2016/05/03 - 2016/07/26
3232
101
TUT
T 4:30PM - 5:20PM
RCH   302
Staff
2016/05/03 - 2016/05/03

T 4:30PM - 5:20PM
RCH   302
Staff
2016/05/17 - 2016/05/17

T 4:30PM - 5:20PM
RCH   302
Staff
2016/05/31 - 2016/05/31

T 4:30PM - 5:20PM
RCH   302
Staff
2016/06/14 - 2016/06/14

T 4:30PM - 5:20PM
RCH   302
Staff
2016/06/28 - 2016/06/28

T 4:30PM - 5:20PM
RCH   302
Staff
2016/07/12 - 2016/07/12

T 4:30PM - 5:20PM
RCH   302
Staff
2016/07/26 - 2016/07/26
Exam Information

ECE 498A - Engineering Design Project
Status  Units   Grading Grade
Enrolled
0.50
Numeric Grading Basis

Class Nbr   Section Component   Days & Times    Room    Instructor  Start/End Date
3233
001
PRJ
T 5:30PM - 6:20PM
RCH   101
Dana Kulic, 
Daniel Davison
2016/05/02 - 2016/07/26
Exam Information

Printer Friendly Page
    My Academics                Course Selection (Undergrad Only)               Enroll              Go Pass  
    My Class Schedule               Add             Drop                Swap                Component Swap              Appointments                Search For Classes  
GO!

**Comment by Trinovantes** [comment]
Thanks, I'll take a look at it tonight

**Comment by Trinovantes** [comment]
@johnwyz88 This should be fixed on the live site now. Don't forget to refresh your browser cache. Thanks for reporting this bug.
